
import { Timestamp } from 'firebase/firestore';

export type Doctor = {
  id: string;
  name: string;
  speciality: string[]; // array of strings
  timings: string;
  room_no: string;
  available: boolean;
};

export type Patient = {
  id: string;
  name: string;
  issues: string[];
  type: string; // Using union type for specific values
  date: Timestamp | Date;
  ipd_no: string;
  doctor: string;
  staff: string[];
  medicines: string[];
};

export type SupplyItem = {
  id: string;
  item_id: string;
  name: string;
  type: string;
  delivery_date: Timestamp | Date;
  expiry_date: Timestamp | Date;
  expired: boolean;
};

export type BloodItem = {
  id: string;
  item_id: string;
  blood_group: string;
  type: string;
  delivery_date: Timestamp | Date;
  expiry_date: Timestamp | Date;
  expired: boolean;
};

export type RobotData = {
  obstacle: {
    left: number;
    mid: number;
    right: number;
  };
  direction?: string; // Optional to handle cases where it might not be available
};

export type MedicineBatch = {
  id: string;
  batchNumber: string;
  expirationDate: Timestamp | Date;
  manufacturer: string;
  quantity: number;
};

export type Medicine = {
  id: string;
  name: string;
  batches: MedicineBatch[];
};


export type BloodInventory = {
  [key in BloodGroup]: {
    available: number;
    critical: number;
  };
};

export type BloodGroup = "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";

// Donation Statistics Type
export type DonationStat = {
  id?: string; // Added for Firestore document ID
  name: string;
  value: number;
  color: string;
  createdAt?: Timestamp; // Added for tracking when record was created
};

// Donor Demographics Type
export type DonorAgeGroup = {
  id?: string; // Added for Firestore document ID
  name: string;
  value: number;
  color: string;
  updatedAt?: Timestamp; // Added for tracking last update
};

// Monthly Donations Type
export type MonthlyDonation = {
  id?: string; // Added for Firestore document ID
  month: string;
  donations: number;
  year?: number; // Added for multi-year tracking
  createdAt?: Timestamp;
};

// Blood Request Type
export type BloodRequest = {
  id?: string; // Auto-generated by Firestore
  bloodGroup: BloodGroup;
  quantity: number;
  priority: "High" | "Medium" | "Low";
  department: string;
  requester: string;
  status: "Pending" | "Fulfilled" | "Cancelled";
  requestedAt: Timestamp;
  fulfilledAt?: Timestamp;
  notes?: string;
};

